[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
[[bin]]
name = "day1"
path = "day1.rs"

[[bin]]
name = "day2"
path = "day2.rs"

[[bin]]
name = "day2part1"
path = "day2part1.rs"

